// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <functional>

namespace naomi_gen {

enum class package : int {
    STORE_LIST,
    PRODUCT_LIST,
};

}  // namespace naomi_gen

namespace std {

template <>
struct hash<::naomi_gen::package> {
    size_t operator()(::naomi_gen::package type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
