// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sandwich.djinni

#pragma once

#include <memory>

namespace naomi_gen {

class Recipe;

class Sandwich {
public:
    virtual ~Sandwich() {}

    virtual std::shared_ptr<Recipe> get_recipe() = 0;

    static std::shared_ptr<Sandwich> get_instance();
};

}  // namespace naomi_gen
