// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include <memory>
#include <string>

namespace naomi_gen {

class Runnable;

class Service {
public:
    virtual ~Service() {}

    virtual void on_create() = 0;

    virtual void on_start(const std::string & name, const std::shared_ptr<Runnable> & runnable) = 0;
};

}  // namespace naomi_gen
