// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include <memory>
#include <string>

namespace naomi_gen {

class Chef;
class Handler;
class Service;

class Api {
public:
    virtual ~Api() {}

    virtual std::shared_ptr<Chef> get_chef() = 0;

    static std::shared_ptr<Api> get_instance(const std::string & root, const std::shared_ptr<Handler> & handler, const std::shared_ptr<Service> & service);
};

}  // namespace naomi_gen
