// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include <memory>
#include <string>
#include <unordered_map>

namespace naomi_gen {

class ServiceBinder;
enum class package;

class Dish {
public:
    virtual ~Dish() {}

    virtual void serve(package package_list, const std::unordered_map<std::string, std::string> & params, const std::shared_ptr<ServiceBinder> & binder) = 0;
};

}  // namespace naomi_gen
