// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include <memory>

namespace naomi_gen {

class Response;
enum class intention;

class Dish {
public:
    virtual ~Dish() {}

    virtual void serve(intention intent, const std::shared_ptr<Response> & callback) = 0;
};

}  // namespace naomi_gen
