// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include <functional>

namespace naomi_gen {

enum class load_type : int {
    LAZY,
    STRICT,
    STATIC,
};

}  // namespace naomi_gen

namespace std {

template <>
struct hash<::naomi_gen::load_type> {
    size_t operator()(::naomi_gen::load_type type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
