// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <functional>

namespace naomi_gen {

enum class module : int {
    CONFIG,
    CATALOG,
    CHECKOUT,
};

}  // namespace naomi_gen

namespace std {

template <>
struct hash<::naomi_gen::module> {
    size_t operator()(::naomi_gen::module type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
