// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include <memory>

namespace naomi_gen {

class Dish;
enum class menu;

class Recipe {
public:
    virtual ~Recipe() {}

    virtual std::shared_ptr<Dish> get_dish() = 0;

    virtual menu get_menu() = 0;
};

}  // namespace naomi_gen
