// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include <string>

namespace naomi_gen {

class Response {
public:
    virtual ~Response() {}

    virtual void on_load(const std::string & message) = 0;
};

}  // namespace naomi_gen
