// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

namespace naomi_gen {

class Runnable {
public:
    virtual ~Runnable() {}

    virtual void run() = 0;
};

}  // namespace naomi_gen
