// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

namespace naomi_gen {

class SimpleCursor {
public:
    virtual ~SimpleCursor() {}
};

}  // namespace naomi_gen
