// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import <Foundation/Foundation.h>
@class SMApi;
@class SMSandwich;
@protocol SMHandler;
@protocol SMService;


@interface SMApi : NSObject

- (nullable SMSandwich *)getApplication;

+ (nullable SMApi *)getInstance:(nonnull NSString *)root
                        handler:(nullable id<SMHandler>)handler
                        service:(nullable id<SMService>)service;

@end
