// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import "SMPackage.h"
#import <Foundation/Foundation.h>
@protocol SMServiceBinder;


@interface SMDish : NSObject

- (void)serve:(SMPackage)packageList
       params:(nonnull NSDictionary<NSString *, NSString *> *)params
       binder:(nullable id<SMServiceBinder>)binder;

@end
