// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import <Foundation/Foundation.h>
@class SMRunnable;


@protocol SMHandler

- (void)post:(nullable SMRunnable *)runnable;

@end
