// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import "SMMenu.h"
#import <Foundation/Foundation.h>
@class SMDish;


@interface SMRecipe : NSObject

- (nullable SMDish *)getDish;

- (SMMenu)getMenu;

@end
