// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import <Foundation/Foundation.h>
@class SMRunnable;


@protocol SMService

- (void)onCreate;

- (void)onStart:(nonnull NSString *)name
       runnable:(nullable SMRunnable *)runnable;

@end
