// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import "SMIntention.h"
#import <Foundation/Foundation.h>
@protocol SMResponse;


@interface SMDish : NSObject

- (void)serve:(SMIntention)intent
     callback:(nullable id<SMResponse>)callback;

@end
