// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SMLoadType)
{
    SMLoadTypeLAZY,
    SMLoadTypeSTRICT,
    SMLoadTypeSTATIC,
};
