// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import "SMModule.h"
#import <Foundation/Foundation.h>
@class SMDish;


@interface SMRecipe : NSObject

- (nullable SMDish *)getDish;

- (SMModule)getModule;

@end
