// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import <Foundation/Foundation.h>
@class SMConfig;


@interface SMRecipe : NSObject

- (nonnull NSArray<SMConfig *> *)getConfigurations;

@end
