// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import "SMModule.h"
#import <Foundation/Foundation.h>
@class SMDish;
@class SMRecipe;


@interface SMSandwich : NSObject

- (nonnull NSString *)getVersion;

- (nullable SMDish *)grab:(SMModule)module;

- (void)addRecipe:(nullable SMRecipe *)recipe;

@end
