// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sandwich.djinni

#import <Foundation/Foundation.h>
@class SMRecipe;
@class SMSandwich;


@interface SMSandwich : NSObject

- (nullable SMRecipe *)getRecipe;

+ (nullable SMSandwich *)getInstance;

@end
