// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import "SMLoadType.h"
#import <Foundation/Foundation.h>
@class SMSimpleCursor;


@protocol SMServiceBinder

- (SMLoadType)loadType;

- (void)onError:(nonnull NSString *)message;

- (void)onLoad:(nonnull NSString *)message
         cache:(BOOL)cache
        cursor:(nullable SMSimpleCursor *)cursor;

@end
