// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#import <Foundation/Foundation.h>


@interface SMSimpleCursor : NSObject

- (nonnull NSString *)toJsonString;

@end
