// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

package com.siliconbear.kitchen;

public abstract class Response {
    public abstract void onLoad(String message);
}
