// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

package com.siliconbear.kitchen;

public abstract class ServiceBinder {
    public abstract LoadType loadType();

    public abstract void onError(String message);

    public abstract void onLoad(String message, boolean cache, SimpleCursor cursor);
}
