// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

package com.siliconbear.kitchen;

public abstract class Service {
    public abstract void onCreate();

    public abstract void onStart(String name, Runnable runnable);
}
