// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include "djinni_support.hpp"
#include "module.hpp"

namespace djinni_generated {

class NativeModule final : ::djinni::JniEnum {
public:
    using CppType = ::naomi_gen::module;
    using JniType = jobject;

    using Boxed = NativeModule;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeModule>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeModule>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeModule() : JniEnum("com/siliconbear/kitchen/Module") {}
    friend ::djinni::JniClass<NativeModule>;
};

}  // namespace djinni_generated
