// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include "djinni_support.hpp"
#include "response.hpp"

namespace djinni_generated {

class NativeResponse final : ::djinni::JniInterface<::naomi_gen::Response, NativeResponse> {
public:
    using CppType = std::shared_ptr<::naomi_gen::Response>;
    using CppOptType = std::shared_ptr<::naomi_gen::Response>;
    using JniType = jobject;

    using Boxed = NativeResponse;

    ~NativeResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeResponse>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeResponse>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeResponse();
    friend ::djinni::JniClass<NativeResponse>;
    friend ::djinni::JniInterface<::naomi_gen::Response, NativeResponse>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::naomi_gen::Response
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void on_load(const std::string & message) override;

    private:
        friend ::djinni::JniInterface<::naomi_gen::Response, ::djinni_generated::NativeResponse>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/siliconbear/kitchen/Response") };
    const jmethodID method_onLoad { ::djinni::jniGetMethodID(clazz.get(), "onLoad", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
