// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#include "NativeConfig.hpp"  // my header
#include "NativeDish.hpp"
#include "NativeModule.hpp"

namespace djinni_generated {

NativeConfig::NativeConfig() : ::djinni::JniInterface<::naomi_gen::Config, NativeConfig>("com/siliconbear/kitchen/Config$CppProxy") {}

NativeConfig::~NativeConfig() = default;


CJNIEXPORT void JNICALL Java_com_siliconbear_kitchen_Config_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::naomi_gen::Config>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_siliconbear_kitchen_Config_00024CppProxy_native_1getDish(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::naomi_gen::Config>(nativeRef);
        auto r = ref->get_dish();
        return ::djinni::release(::djinni_generated::NativeDish::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_siliconbear_kitchen_Config_00024CppProxy_native_1getModule(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::naomi_gen::Config>(nativeRef);
        auto r = ref->get_module();
        return ::djinni::release(::djinni_generated::NativeModule::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
