// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#pragma once

#include "config.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeConfig final : ::djinni::JniInterface<::naomi_gen::Config, NativeConfig> {
public:
    using CppType = std::shared_ptr<::naomi_gen::Config>;
    using CppOptType = std::shared_ptr<::naomi_gen::Config>;
    using JniType = jobject;

    using Boxed = NativeConfig;

    ~NativeConfig();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeConfig>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeConfig>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeConfig();
    friend ::djinni::JniClass<NativeConfig>;
    friend ::djinni::JniInterface<::naomi_gen::Config, NativeConfig>;

};

}  // namespace djinni_generated
