// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#include "NativeSimpleCursor.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSimpleCursor::NativeSimpleCursor() : ::djinni::JniInterface<::naomi_gen::SimpleCursor, NativeSimpleCursor>("com/siliconbear/kitchen/SimpleCursor$CppProxy") {}

NativeSimpleCursor::~NativeSimpleCursor() = default;


CJNIEXPORT void JNICALL Java_com_siliconbear_kitchen_SimpleCursor_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::naomi_gen::SimpleCursor>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_siliconbear_kitchen_SimpleCursor_00024CppProxy_native_1toJsonString(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::naomi_gen::SimpleCursor>(nativeRef);
        auto r = ref->to_json_string();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
