// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#include "NativeDish.hpp"  // my header
#include "NativeIntention.hpp"
#include "NativeResponse.hpp"

namespace djinni_generated {

NativeDish::NativeDish() : ::djinni::JniInterface<::naomi_gen::Dish, NativeDish>("com/siliconbear/kitchen/Dish$CppProxy") {}

NativeDish::~NativeDish() = default;


CJNIEXPORT void JNICALL Java_com_siliconbear_kitchen_Dish_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::naomi_gen::Dish>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_siliconbear_kitchen_Dish_00024CppProxy_native_1serve(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_intent, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::naomi_gen::Dish>(nativeRef);
        ref->serve(::djinni_generated::NativeIntention::toCpp(jniEnv, j_intent),
                   ::djinni_generated::NativeResponse::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
