// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

#include "NativeResponse.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeResponse::NativeResponse() : ::djinni::JniInterface<::naomi_gen::Response, NativeResponse>() {}

NativeResponse::~NativeResponse() = default;

NativeResponse::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeResponse::JavaProxy::~JavaProxy() = default;

void NativeResponse::JavaProxy::on_load(const std::string & c_message) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeResponse>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLoad,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_message)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
