// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

package com.siliconbear.kitchen;

public abstract class Handler {
    public abstract void post(Runnable runnable);
}
