// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from chef.djinni

package com.siliconbear.kitchen;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Recipe {
    public abstract ArrayList<Config> getConfigurations();

    private static final class CppProxy extends Recipe
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ArrayList<Config> getConfigurations()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getConfigurations(this.nativeRef);
        }
        private native ArrayList<Config> native_getConfigurations(long _nativeRef);
    }
}
